services:
  db:
    image: postgres:16
    container_name: mortgage-assistant-db

    environment:
      POSTGRES_USER: mortgage_user
      POSTGRES_PASSWORD: mortgage_password
      POSTGRES_DB: mortgage_assistant

    ports:
      - "5432:5432"

    volumes:
      - mortgage_pg_data:/var/lib/postgresql/data

volumes:
  mortgage_pg_data: