"""add lender chunk embeddings

Revision ID: 6bdcf4731637
Revises: 7d64bc48bd89
Create Date: 2026-07-10 18:49:42.579401

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '6bdcf4731637'
down_revision: Union[str, Sequence[str], None] = '7d64bc48bd89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lender_chunks', sa.Column('embedding', Vector(1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lender_chunks', 'embedding')
    # ### end Alembic commands ###
