"""create lender chunks table

Revision ID: 7d64bc48bd89
Revises: 36487c90702e
Create Date: 2026-07-09 13:14:45.780801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d64bc48bd89'
down_revision: Union[str, Sequence[str], None] = '36487c90702e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lender_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lender_file_id', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.Text(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lender_file_id'], ['lender_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lender_chunks_id'), 'lender_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lender_chunks_id'), table_name='lender_chunks')
    op.drop_table('lender_chunks')
    # ### end Alembic commands ###
